### ISSUE TITLE
y-axis artifact when switching columns on horizontal bar chart

### ISSUE THREAD

**Issue by tkb** [datawrapper/datawrapper#179]
Working on this chart:

https://datawrapper.dwcdn.net/f5KIv/3/

It looks fine when "2013" is selected:

![image](https://cloud.githubusercontent.com/assets/192869/12201260/371413d6-b5f1-11e5-95a9-eeda180db657.png)

But when i pick another year, I see the old y-axis as an artifact in the chart:

![image](https://cloud.githubusercontent.com/assets/192869/12201282/5538127c-b5f1-11e5-9a51-5e89042d27eb.png)

And another example:

![image](https://cloud.githubusercontent.com/assets/192869/12201286/6048e448-b5f1-11e5-9ca7-64f09e930676.png)

Running Datawrapper Team, issue present on Chrome / Firefox latest builds for Mac OSX 10.10.5

**Comment by davidkokkelink** [comment]
coincidentally, this was fixed 5 days ago and will be deployed soon :) see commit: https://github.com/datawrapper/datawrapper/commit/41367fbf5454915a0633acb0c0ed54360992ddd1

**Comment by tkb** [comment]
Cool, thanks.

**Comment by davidkokkelink** [comment]
fix was deployed recently.

**Comment by tkb** [comment]
Is there anything I need to do to take advantage of the fixed version? I'm still seeing the problem with: https://datawrapper.dwcdn.net/f5KIv/3/

**Comment by davidkokkelink** [comment]
for the new version to appear in published charts you will have to re-publish the chart inside datawrapper once. then it will take a couple of minutes to propagate to all servers.
